apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aimmopostcluster-2a15"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aimmopostcluster-2a15"
  template:
    metadata:
      labels:
        app: "aimmopostcluster-2a15"
    spec:
      containers:
        - name: "aimmopostcluster-2a15"
          image: "aimmoregistry.azurecr.io/aimmopostcluster"
          ports:
          - containerPort: 5000