apiVersion: v1
kind: Service
metadata:
    name: "aimmopostcluster-1a56"
    labels:
        app: "aimmopostcluster-1a56"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "aimmopostcluster-1a56"