apiVersion: v1
kind: Service
metadata:
    name: "aimmopostcluster-907a"
    labels:
        app: "aimmopostcluster-907a"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aimmopostcluster-907a"