on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n aimmopost1 -g aimmopost1b625-rg --location "Korea Central" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n aimmopost1 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n aimmopost1 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n aimmopost1 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: aimmopost1.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aimmopost1.azurecr.io/aimmopostcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push aimmopost1.azurecr.io/aimmopostcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_aimmopostcluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aimmopost-clustera0d2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aimmopost-clustera0d2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aimmopost-clustera0d2
        container-registry-url: aimmopost1.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: aimmopostcludockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aimmopost-clustera0d2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aimmopost1.azurecr.io/aimmopostcluster:${{ github.sha }}
        imagepullsecrets: |
          aimmopostcludockerauth   
