on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aimmopost1.azurecr.io
        username: ${{ secrets.acr_aimmopost1_username }}
        password: ${{ secrets.acr_aimmopost1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aimmopost1.azurecr.io/aimmopostcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push aimmopost1.azurecr.io/aimmopostcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aimmopostcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aimmopost-clusterb2fe | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aimmopost-clusterb2fe`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aimmopost-clusterb2fe
        container-registry-url: aimmopost1.azurecr.io
        container-registry-username: ${{ secrets.acr_aimmopost1_username }}
        container-registry-password: ${{ secrets.acr_aimmopost1_password }}
        secret-name: aimmopostcludockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aimmopost-clusterb2fe
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aimmopost1.azurecr.io/aimmopostcluster:${{ github.sha }}
        imagepullsecrets: |
          aimmopostcludockerauth
